DEBUG 2020-12-21 17:49:28.399 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-21 17:49:28.400 UTC: 	 Running on: Linux lxplus7115.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-21 17:49:28.400 UTC: 	 Executing command: 'status'
DEBUG 2020-12-21 17:49:28.400 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/achhetri/.crab3
ERROR 2020-12-21 17:49:28.401 UTC: 	 Error: {DeltaR_Hist_FatJet1_wrt_jet1, is not a valid CRAB project directory.
ERROR 2020-12-21 17:49:28.401 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: {DeltaR_Hist_FatJet1_wrt_jet1, is not a valid CRAB project directory.
INFO 2020-12-21 17:49:28.407 UTC: 	 Log file is /afs/cern.ch/user/a/achhetri/NANO_AOD/CMSSW_10_6_8/src/WTopScalefactorProducer/Skimmer/NANOcrab/crab_Tprime_v5_NANo_AOD_106X/crab.log
